### PR TITLE
New param `configFileName` and `async`. Some bug fix.

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
- Fixed tsconfig.json target param.
- Updated typescript definition versions.
- Added new param `configFileName?: string = 'tsconfig.json';.
- Fixed typescript compiler error (as glob.IOptions) and removed root.
- fs.writeFile changed to sync method.

### CODE REVIEW

**Comment by wjohnsto** [comment]
@GiedriusGrabauskas Wow man, thanks for the work. I'll look at this and hopefully merge it in soon!

**Comment by DovydasNavickas** [comment]
@wjohnsto, could you check the PR? It'd be nice to have @GiedriusGrabauskas changes in npm :smile: Thanks! :clap:

**Comment by wjohnsto** [comment]
Changes are in v0.4.0

**Comment by GiedriusGrabauskas** [comment]
:+1:  Cool, thanks ;)

**Pull request merged**
