### PR TITLE
Alpha sorting

### PR DESCRIPTION
**Pull request by brahms**
https://github.com/wjohnsto/tsconfig-glob/issues/3

Just added alpha sorting before going through the current sort function, so the filenames stay in order.

### CODE REVIEW

**Comment by henryptung** [comment]
Hey!

I'm not maintainer on this, but if I can offer a thought based on looking at this earlier:

I think the issue here isn't that the array isn't presorted before passing into the sort-d.ts-to-top comparator. It should be, glob inherently sorts results before returning.

If I understand correctly, the issue is that Node's (or Javascript's) Array.sort() implementation is not stable, meaning that it has no guarantee of preserving original array order. In this case, adding the extra sort call before the sort-d.ts-to-top call doesn't have an effect, because the unstable sort can still destroy the order that was just created.

My guess is we probably want to use a stable sort like https://www.npmjs.com/package/stable, which allows the original order to be preserved as much as possible, and makes the output order fully specified (inheriting as much order from glob as possible).

**Comment by brahms** [comment]
@henryptung hey thanks, I didn't realize the sorting wasn't stable. I've added the stable package and used it just like previously, sorting by alpha, than sorting by file type.

**Comment by wjohnsto** [comment]
@brahms At a glance this looks good, give me some time to look over it and I'll merge it in, thanks!

**Comment by wjohnsto** [comment]
There were some problems with this PR, but I have fixed them and merged into master. working with v0.3.0 now.

**Pull request closed without merging**
